language: bash

install:
  - sudo apt-get install -y m4

services:
  - docker

script: |
  : ${VERSION:=${TRAVIS_TAG#v}}
  : ${VERSION:=$TRAVIS_BRANCH}
  make push VERSION=$VERSION > make.log
  status=$?
  if [ $status -ne 0 ]
  then
      echo "========================================================================"
      echo Job exited with status $status. Log follows:
      echo "========================================================================"
      tail --lines=4K make.log
  fi
  ( exit $status )
