language: bash

install:
  - sudo apt-get install -y m4

services:
  - docker

script: |
  : ${VERSION:=${TRAVIS_TAG#v}}
  : ${VERSION:=$TRAVIS_BRANCH}
  BRANCH=$(
      git for-each-ref --contains $TRAVIS_BRANCH |
      awk '($2 == "commit"){print $3}' |
      sed -n 's_^refs/heads/__p' |
      head -n1)
  make push VERSION=$VERSION BRANCH=$BRANCH > make.log
  status=$?
  if [ $status -ne 0 ]
  then
      echo "========================================================================"
      echo Job exited with status $status. Log follows:
      echo "========================================================================"
      tail --lines=4K make.log
  fi
  ( exit $status )
