language: bash

install:
  - sudo apt-get install -y m4

services:
  - docker

script:
  - make pull > make.log || true
  - make login push >> make.log ; echo $? > make.status
  - [ "$(< make.status)" -eq 0 ] || tail --lines=4K make.log
  - [ "$(< make.status)" -eq 0 ]
