language: bash

install:
  - sudo apt-get install -y m4

services:
  - docker

script: |
  : ${VERSION:=${TRAVIS_TAG#v}}
  : ${VERSION:=$TRAVIS_BRANCH}
  make push VERSION=$VERSION > make.log
  status=$?
  test $status -eq 0 || tail --lines=4K make.log
  test $status -eq 0
