language: bash

install:
  - sudo apt-get install -y m4

services:
  - docker

stages:
  - name: deploy
    if: tag IS present

jobs:
  include:
    - script:
        - make pull > make.log || true
        - make >> make.log ; echo $? > make.status
        - test "$(cat make.status)" -eq 0 || tail --lines=4K make.log
        - test "$(cat make.status)" -eq 0
    - stage: deploy
      script: make login push
