language: bash

install:
  - sudo apt-get install -y m4

services:
  - docker

stages:
  - name: deploy
    if: tag IS present

jobs:
  include:
    - if: tag IS present
      script: make pullpush > make.log ; echo $? > make.status
    - if: tag IS NOT present
      script: make pullpush VERSION=master > make.log ; echo $? > make.status
    - stage: report
      script:
        - test "$(cat make.status)" -eq 0 || tail --lines=4K make.log
        - test "$(cat make.status)" -eq 0
